version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/nextjs/Dockerfile
    image: next-app
    container_name: next-app
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
      - ./front/node_modules:/app/node_modules
    command: sh -c "npm run dev"
    environment:
      TZ: Asia/Tokyo
    restart: always
    tty: true
    stdin_open: true

  api:
    build:
      context: .
      dockerfile: dockerfiles/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back/api:/app
    ports:
      - 8000:3000
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres-data:
  node_modules:
