version: "3.7"

services:
  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../api:/app
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres-data:
